### PR TITLE
Collect search providers into a sub-menu

### PR DESCRIPTION
**Pull request by James-E-A**
The existing array of providers popping open looks very visually disruptive; I believe that condensing these into a "directory" is appropriate.

### CODE REVIEW

**Review by LouCypher — CHANGES_REQUESTED** [review]
Good idea. Can you bump the `@version` to `2.2`?
Thanks.

**Comment by James-E-A** [comment]
Certainly.

Do you want that as a separate commit, or force/merged?

**Comment by James-E-A** [comment]
Actually, put this PR on the back burner for now. It looks like this broke something. :sweat_smile: Don't commit it!

**Comment by James-E-A** [comment]
I believe it's ready now. [EDIT: sorry for the double-ping; I thought that was a refresh button…]

**Pull request merged**
